// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AllocState struct {
	ID          int32
	LastTokenID int64
}

type Lease struct {
	TokenID   int64
	PeerID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Nonce struct {
	ID        pgtype.UUID
	PeerID    string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Used      bool
	UsedAt    pgtype.Timestamptz
}
